version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: update things
          command: |
              pip install --upgrade pip
              pip install -U virtualenv
              pip install -U tox
              pip list

      - run:
          name: run tests
          command: tox
